---
id: workshop-tutorial
base_name: scenario
tags:
- rabbit
- oss_gate
- workshop
presentation_date: 2026-02-13
version: 2026.2.13.0
licenses:
- CC-BY-SA-4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
source_code_uri: https://github.com/oss-gate/workshop/tree/master/tutorial/scenario
author:
  markup_language: :rd
  name: OSS Gate
  email: kou+oss-gate@cozmixng.org
  rubygems_user: oss-gate
  slideshare_user: 
  speaker_deck_user: 
